# SakuraSpawn: devuelve al spawn si caen al vacío (Y <= -70)
every 5 ticks:
    loop all players:
        loop-player's world's name is "SakuraSpawn"
        y-coordinate of loop-player <= -70:
            set {_loc} to location(23.478, -61, -92.564, world "SakuraSpawn")
            set yaw of {_loc} to -89.2
            set pitch of {_loc} to -0.8
            teleport loop-player to {_loc}
            send "&aTe devolvimos al spawn." to loop-player
