#Minecraft server properties
#Fri Dec 26 18:34:09 UTC 2025
accepts-transfers=false
allow-flight=false
broadcast-console-to-ops=true
broadcast-rcon-to-ops=true
bug-report-link=
debug=true
difficulty=easy
enable-code-of-conduct=false
enable-jmx-monitoring=true
enable-query=true
enable-rcon=true
enable-status=true
enforce-secure-profile=true
enforce-whitelist=false
entity-broadcast-range-percentage=100
force-gamemode=false
function-permission-level=2
gamemode=survival
generate-structures=true
generator-settings={}
hardcore=false
hide-online-players=false
initial-disabled-packs=
initial-enabled-packs=vanilla
level-name=world
level-seed=
level-type=minecraft\:normal
log-ips=true
management-server-allowed-origins=
management-server-enabled=false
management-server-host=localhost
management-server-port=0
management-server-secret=rmomLLToJCFc3KQCgi5MkL8rD9H5ghdmiJBYhbOc
management-server-tls-enabled=true
management-server-tls-keystore=
management-server-tls-keystore-password=
max-chained-neighbor-updates=1000000
max-players=20
max-tick-time=60000
max-world-size=29999984
motd=≪≣ §lEl server§r más §4§n§oh§6§n§oe§e§n§ot§a§n§oe§9§n§or§5§n§oo§r de Minecraft ≣≫\n════════════════════════════════════
network-compression-threshold=256
online-mode=false
op-permission-level=4
pause-when-empty-seconds=60
player-idle-timeout=0
prevent-proxy-connections=false
query.port=25565
rate-limit=0
rcon.password=509584d7b08eb0f1223a72e7
rcon.port=25575
region-file-compression=deflate
require-resource-pack=true
resource-pack=https\://download.mc-packs.net/pack/075a6f89527b8b09b8e6a6009c69f118dc1ef460.zip
resource-pack-id=
resource-pack-prompt=§lSe va a descargar un paquete de texturas ^^ §r\n§7Es para mejorar tu experiencia en el server de Ferxas. §eNo tienes opción, sino no puedes entrar al server
resource-pack-sha1=075a6f89527b8b09b8e6a6009c69f118dc1ef460
server-ip=
server-port=25565
simulation-distance=10
spawn-protection=16
status-heartbeat-interval=0
sync-chunk-writes=true
text-filtering-config=
text-filtering-version=0
use-native-transport=true
view-distance=10
white-list=false