min-chest-content: 3
max-chest-content: 6
min-barrel-content: 4
max-barrel-content: 7
min-trapped-chest-content: 4
max-trapped-chest-content: 7
num-supply-drops: 1
min-supply-drop-content: 2
max-supply-drop-content: 6
players-per-team: 1
game-time: 900
countdown: 20
grace-period: 30
supplydrop:
  interval: 120
chestrefill:
  interval: 180
auto-start:
  enabled: true
  players: 4
  delay: 15
min-players: 2
voting: false
display-scoreboard: true
display-bossbar: true
break-blocks:
  enabled: false
  drop: true
  allowed-blocks:
    - GRASS_BLOCK
    - DIRT
border:
  size: 410
  start-time: 600
  end-time: 840
  final-size: 100
  center-x: -4
  center-z: 19
custom-commands:
  enabled: true
  start:
    global:
      - "mv modify HGPlay set pvp false"
      - "hgarena busy HGPlay"
    foreach-player:
      - "hgleave remove {winner}"
  end:
    global:
      - "hgarena waiting HGPlay"
    foreach-winner: []
